name: Release NPM Package

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  test:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4

      - name: Setup Node.js ðŸ”¨
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies ðŸ“¦
        run: |
          yarn install
          yarn build

      - name: Test ðŸ§ª
        run: yarn test:ci

  publish:
    needs: test
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ðŸ›Žï¸
      uses: actions/checkout@v4

    - name: Setup Node.js ðŸ”¨
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies ðŸ“¦
      run: |
        yarn install
        mkdir -p dist

    - name: Compile & Generate Types ðŸ“š
      run: |
        yarn compile
        yarn hardhat export-abi
        cp build/abi/zAceWebClient.json dist/zAceWebClient.abi.json
        yarn wagmi generate
        yarn typechain --target ethers-v6 --out-dir dist/ethers-v6 dist/*.abi.json
        yarn typechain --target ethers-v5 --out-dir dist/ethers-v5 dist/*.abi.json

    - name: Prepare Deploy ðŸ“¦
      env:
        VERSION: ${{ github.ref_name }}
      run: |
        cp contracts.json ./dist
        cat .github/assets/package.mainnet.json | jq --arg ver ${{ env.VERSION }} '.version = $ver | .version |= ltrimstr("v")' > dist/package.json

    - name: Deploy ðŸš€
      working-directory: dist
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_KEY }}
      run: |
        npm install
        npm ci
        npm publish --access public --tag latest
